amcl:
  ros__parameters:
    use_sim_time: false
    map_type: 'occupancy'
    ...

bt_navigator:
  ros__parameters:
    ...
    
planner_server:
  ros__parameters:
    ...
    
controller_server:
  ros__parameters:
    ...
    
waypoint_follower:
  ros__parameters:
    ...
